defaults:
  - data: face_mask
  - preprocessing: default
  - model: fasterrcnn_resnet50_fpn
  - training: h100
  - logging: mlflow
  - inference: default
  - _self_

seed: 24

paths:
  data_root: data
  plots_dir: plots
  models_dir: models
  checkpoints_dir: checkpoints
